version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: bsc-redis
    ports:
      - "6379:6379"    # Redis
      - "8001:8001"    # RedisInsight (Web UI)
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant - Vector Database para teste
  qdrant:
    image: qdrant/qdrant:latest
    container_name: bsc-qdrant
    ports:
      - "6333:6333"    # REST API
      - "6334:6334"    # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Weaviate - Vector Database para teste
  weaviate:
    image: semitechnologies/weaviate:1.24.1
    container_name: bsc-weaviate
    ports:
      - "8080:8080"    # REST API
      - "50051:50051"  # gRPC API
    volumes:
      - weaviate-data:/var/lib/weaviate
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=text2vec-openai,generative-openai
      - CLUSTER_HOSTNAME=node1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bsc-agent
    ports:
      - "8501:8501"    # Streamlit
      - "8000:8000"    # FastAPI (opcional)
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0

volumes:
  redis-data:
    driver: local
  qdrant-data:
    driver: local
  weaviate-data:
    driver: local
